/*
* TweetDeck software is protected by copyright worldwide, and may be used only
* in accordance with the Terms of Service found at http://www.tweetdeck.com
*/
TD={bg:{}};TD.bg.init=function(){TD.bg.contextMenu.init()};var theTab=null;function handlePageChange(a){if(a.url==chrome.extension.getURL("templates/default.html"))if(theTab){if(a.id!=theTab.id){console.log("Duplicate TweetDeck page");chrome.tabs.remove(a.id);TD.bg.utils.showTDTab()}}else{console.log("TweetDeck page created");theTab=a}else theTab&&a.id==theTab.id&&handlePageDeath(a.id)}
function handlePageDeath(a){if(theTab&&a==theTab.id){console.log("TweetDeck page closed");theTab=null;for(var c in TD.bg.streamEngines){TD.bg.streamEngines[c].stop();delete TD.bg.streamEngines[c]}}}chrome.tabs.onCreated.addListener(function(a){handlePageChange(a)});chrome.tabs.onUpdated.addListener(function(a,c,d){c.url&&handlePageChange(d)});chrome.tabs.onRemoved.addListener(function(a){handlePageDeath(a)});TD.bg.utils={};
TD.bg.utils.getActiveTabWindow=function(){for(var a=chrome.extension.getViews(),c,d=0;d<a.length;d++){c=a[d];if(c.location.href==theTab.url)return c}};TD.bg.utils.showTDTab=function(){if(theTab){var a=function(c){c.focused||chrome.windows.update(c.id,{focused:true})};chrome.tabs.get(theTab.id,function(c){theTab=c;chrome.windows.get(c.windowId,a)});chrome.tabs.update(theTab.id,{selected:true})}};
TD.bg.utils.focusOrOpenTDTab=function(a){var c=function(){var d=TD.bg.utils.getActiveTabWindow(),b=function(){d.TD&&d.TD.ready?a(d.TD):setTimeout(b,500)};b()};if(theTab&&theTab.id){TD.bg.utils.showTDTab();c()}else chrome.tabs.create({url:"templates/default.html"},function(){setTimeout(function(){c()},100)})};TD.bg.streamEngines={};
function getStreamEngine(a,c,d,b){if(this.theTab){if(b.id!==this.theTab.id)return null}else handlePageChange(b);if(b=TD.bg.streamEngines[c.key]){b.callback=d;b.log("Recycling old StreamEngine");b.friendsArray&&b._processData(b.friendsArray)}else{b=new TD.bg.StreamEngine(a,c,d);b.log("Making new StreamEngine")}return b}TD.bg.StreamEngine=function(a,c,d){this.url=a;this.account=c;this.callback=d;this.queries={};this.connection=null;TD.bg.streamEngines[c.key]=this};
TD.bg.StreamEngine.prototype={BACKOFF_INTERVAL_MIN:2E4,BACKOFF_INTERVAL_MAX:24E4,_allFriends:false,_queryString:null,_restartRequired:false,_keepaliveTimeout:null,_backoffTimeout:null,_backoffInterval:-1,_failureTime:null,log:function(a){console.log((new Date).getTime().toString()+" "+this.account.username+": "+a)},stop:function(){if(this.connection){this.log("Stopping stream");this.connection.onreadystatechange=null;this.connection.abort();this.connection=null;this._disconnected()}if(this._keepaliveTimeoutID){clearTimeout(this._keepaliveTimeoutID);
this._keepaliveTimeoutID=null}},restart:function(){this.log("Restarting stream");this.stop();this.start()},_backoffHandler:function(){this.log("Backoff complete");clearTimeout(this._backoffTimeout);this._backoffTimeout=null;this.restart()},_processData:function(a){var c=JSON.parse(a);if(c.friends)this.friendsArray=a;this.callback({eventType:"data",data:c})},_disconnected:function(){this.callback({eventType:"disconnect"})},queryActive:function(a){a=a.toLowerCase();return Boolean(this.queries[a])},
addQuery:function(a){var c=a.toLowerCase(),d=["from","to","near","within","since","until","filter","source"],b;if(!this.queries[c]){for(b=0;b<d.length;b++)if(c.indexOf(d[b])!=-1)return;d=new TD.bg.SearchParser(a);this.queries[c]=d;this._queryString=this.constructQueryString(this.queries);this.log("Adding query: "+a);this._restartRequired=true}},addAllFriends:function(){this.log("Connecting to all friends");this.connection&&this.restart();this._allFriends=true},constructQueryString:function(a){var c=
[],d;for(d in a)c.push(a[d].trackQuery);return c.join(",")},removeQuery:function(a){var c=a.toLowerCase();if(this.queryActive(a)){delete this.queries[c];this._queryString=this.constructQueryString(this.queries);this._restartRequired=true}},setStreamAllFriends:function(a){if(a!=this._allFriends){this._allFriends=a;this._restartRequired=true}},start:function(){if(!this.connection&&this._backoffTimeout&&this._backoffInterval+this._failureTime<(new Date).getTime()){this.log("Failsafe for long disconnects");
clearTimeout(this._backoffTimeout);this._backoffTimeout=null}else if(this._backoffTimeout){this.log("Stream already started (waiting for backoff)");this._disconnected();return}if(this.connection){if(this._restartRequired){this._restartRequired=false;this.restart()}}else{this.log("Starting StreamEngine");this._restartRequired=false;var a=0,c=new XMLHttpRequest,d,b=this,f=this.url,e=this._queryString?"?track="+encodeURIComponent(this._queryString):"";if(!this._allFriends){e+=e.length?"&":"?";e+="with=user"}c.open("GET",
f+encodeURIComponent("https://userstream.twitter.com/2/user.json")+e);this.connection=c;c.setRequestHeader("x-td-oauth-key",this.account.oauth_token);c.setRequestHeader("x-td-oauth-secret",this.account.token_secret);c.setRequestHeader("x-td-oauth-service","twitter");c.onreadystatechange=function(){if(c.readyState==4){b.log("Signer HTTP status: "+c.status);if(c.status==200){d=new XMLHttpRequest;var h=JSON.parse(c.responseText);d.open("GET","https://userstream.twitter.com/2/user.json"+e);d.setRequestHeader("Authorization",
h.headers.Authorization);d.setRequestHeader("X-User-Agent","TweakDeck Chrome "+TD.version);d.onreadystatechange=g;d.send();b.connection=d}else b.connection=null}};var g=function(){if(b._keepaliveTimeoutID){clearTimeout(b._keepaliveTimeoutID);b._keepaliveTimeoutID=null}if(d.readyState==2)b.log("Stream HTTP status: "+d.status);else if(d.readyState==3&&d.status==200){b._keepaliveTimeoutID=setTimeout(function(){b.restart()},9E4);b._backoffInterval=-1;b._failureTime=null;var h=d.responseText.slice(a),
i,j;if(h.indexOf("\r")!==-1){i=h.split("\r");h.charAt(h.length-1)!=="\r"&&i.pop();if(i.length){for(j=0;j<i.length;j++)i[j].length>1&&b._processData(i[j]);a+=h.length}}a>5E7&&b.restart()}else if(d.readyState==4){b.log("Connection interrupted");b.stop();if(d.status==200&&!b._failureTime){b.restart();b._failureTime=(new Date).getTime()}else{b._failureTime=(new Date).getTime();if(b._backoffInterval==-1){b._backoffInterval=b.BACKOFF_INTERVAL_MIN;b._backoffInterval+=Math.floor(b.BACKOFF_INTERVAL_MIN*Math.random())}b._backoffTimeout=
setTimeout(function(){b._backoffHandler()},b._backoffInterval);switch(d.status){case 420:b._backoffInterval=Math.min(b._backoffInterval*2,b.BACKOFF_INTERVAL_MAX*3);break;default:b._backoffInterval=Math.min(b._backoffInterval*2,b.BACKOFF_INTERVAL_MAX)}}}};c.send()}}};TD.bg.SearchParser=function(a){this.query=a;this.terms=[];this.init()};TD.bg.SearchParser.prototype.PHRASE="phrase";TD.bg.SearchParser.prototype.NEGATIVE_PHRASE="negPhrase";TD.bg.SearchParser.prototype.AND="and";
TD.bg.SearchParser.prototype.OR="or";TD.bg.SearchParser.prototype.query="";TD.bg.SearchParser.prototype.trackQuery="";TD.bg.SearchParser.prototype.thePhrase="";TD.bg.SearchParser.prototype.type="";
TD.bg.SearchParser.prototype.init=function(){if(!this.trackQuery){var a,c;c=typeof this.query=="string"?this.extractPhrases(this.query):this.query;if(c.length!==0)if(c.length==1){this.thePhrase=c[0].toLowerCase();if(this.thePhrase.charAt(0)=="-"&&this.thePhrase.indexOf(" ")!=-1){this.type=this.NEGATIVE_PHRASE;this.thePhrase=this.thePhrase.slice(1);this.trackQuery=""}else{this.type=this.PHRASE;this.trackQuery=this.thePhrase}}else{var d=0,b=[[]],f=true,e;for(e=0;e<c.length;e++){a=c[e];if(a=="OR"){b[d].push(a);
f=true}else{if(f)b[d].push(a);else{d++;b[d]=[a]}f=false}}if(b.length>1){this.type=this.AND;for(e=0;e<b.length;e++){a=b[e];a.length>0&&this.terms.push(new TD.bg.SearchParser(a))}this.trackQuery=this.calculateANDTrackQuery(b)}else{this.type=this.OR;for(e=0;e<b[0].length;e++){a=b[0][e];if(a!="OR"){this.terms.push(new TD.bg.SearchParser([a]));if(a.charAt(0)!="-"){if(this.trackQuery)this.trackQuery+=",";this.trackQuery+=a}}}}}}};
TD.bg.SearchParser.prototype.calculateANDTrackQuery=function(a){for(var c=[""],d=0;d<a.length;d++){for(var b=a[d],f=[],e=0;e<b.length;e++){var g=b[e];if(g!="OR")if(g.charAt(0)=="-")f=c;else for(var h=0;h<c.length;h++){var i=c[h];i=i?i+" ":"";i+=g;f.push(i)}}c=f}return c.join(",")};
TD.bg.SearchParser.prototype.extractPhrases=function(a){for(var c=[],d=a.split('"'),b=0;b<d.length;b++)if(d[b])if(b%2==1&&b<d.length-1)(a=d[b].trim())&&c.push(a);else for(var f=d[b].split(" "),e=0;e<f.length;e++){a=f[e];(a=a.trim())&&c.push(a)}return c};
TD.bg.SearchParser.prototype.match=function(a,c){var d,b;c||(a=a.toLowerCase());switch(this.type){case this.PHRASE:return a.indexOf(this.thePhrase)!=-1;case this.NEGATIVE_PHRASE:return a.indexOf(this.thePhrase)==-1;case this.AND:for(d=0;d<this.terms.length;d++){b=this.terms[d];if(!b.match(a,true))return false}return true;case this.OR:for(d=0;d<this.terms.length;d++){b=this.terms[d];if(b.match(a,true))return true}return false;default:return false}};
TD.bg.contextMenu=function(){var a={},c=chrome.contextMenus,d=chrome.i18n.getMessage,b=function(f,e){var g;if(f.linkUrl)g=f.linkUrl;else{if(e&&e.title){g=e.title;if(g.length>100)g=g.substr(0,100)+"\u2026";g+=" "}g+=f.pageUrl}TD.bg.utils.focusOrOpenTDTab(function(h){h.ui.compose.showComposeWindow(g+" ",true)})};a.init=function(){c.create({title:d("context_menu_share_page"),onclick:b});c.create({title:d("context_menu_share_link"),onclick:b,contexts:["link"]})};return a}();TD.buildID="bad9b993a497d3a217683bd422287c73dbef2b6f";
TD.version="0.9.7.11";TD.env="chrome";
